### ISSUE TITLE
Dont include API Keys directly in JS code

### ISSUE THREAD

**Issue by anuragdaksh7** [Shikhrrr/My_Projects2#1]
Including them is providing them for free to others.
https://github.com/Shikhrrr/My_Projects2/blob/4ebe87f4056e84669b7a28250a9a23ee0a0735db/WeatherApp/WeatherAppAndTaskList.js#L39C8-L42C5
https://github.com/Shikhrrr/My_Projects2/blob/4ebe87f4056e84669b7a28250a9a23ee0a0735db/Railway/index.js#L11C9-L16C1

**Comment by Shikhrrr** [comment]
Thanks Anurag bhaiya for highlighting this issue. I too want to hide my API keys, but I think its going to create some problems for the users. If I remove the keys from here and commit the changes, then the person using my website wouldn't be able to use it, isn't so? I'd be grateful if you could help me out with this.

**Comment by anuragdaksh7** [comment]
you can use .env files for storing sensitive data but thats available with nodejs, so I believe as of now you should make another file to store all the sensitive value and import it in the main file and mention those secret files in .gitignore

eg.

key.js
```
KEY = "some key"
module.exports = { KEY }
```
main.js
```
import { KEY } from "key.js"
```

.gitignore
```
<path to key.js file>/key.js
```

after this include about the key file and how to recreate it in readme 



it would be easier once you would use enviroment variables (.env)
eg:

```
npm install dotenv
```

.env
```
KEY = "some key"
```

main.js
```
require("dotenv").config();
const KEY = process.env.KEY;
```

**Comment by anuragdaksh7** [comment]
yeah alright, in the meantime i would recommend you go through nodejs

**Comment by Shikhrrr** [comment]
Thanks for the suggestion bhaiya. So can you give me an idea about when can we meet?

**Comment by anuragdaksh7** [comment]
right now i m not there ig i'll let u know

**Comment by Shikhrrr** [comment]
Yup okay

**Comment by anuragdaksh7** [comment]
yeah i'll let you know if i m in college tom

**Comment by Shikhrrr** [comment]
Are you coming this week bhaiya?

**Comment by anuragdaksh7** [comment]
yeah (not regularly), can u drop a message on whatsapp?

**Comment by anuragdaksh7** [comment]
yeah i dm'ed you on linkedin
